### ISSUE TITLE
Add timestamp to total fees burned

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/ethereum-burn-stats#10]
We know the EIP 1559 block was activated, would be nice to showcase that timestamp there.

**Comment by abdulqgg** [comment]
Hey, could i tackle this as my first issue? Thanks!

**Comment by mohamedmansour** [comment]
Hey, that could require multiple PRs,

1) Refactor [ActivationCountdown](https://github.com/mohamedmansour/ethereum-burn-stats/blob/main/frontend/src/pages/Dashboard.tsx#L52) so that `timePerBlockInMs` is part of the [EthereumContext](https://github.com/mohamedmansour/ethereum-burn-stats/blob/main/frontend/src/contexts/EthereumContext.tsx) so that we know the average time it takes to process one block and it is cached once per react context.  Then for [ActivationCountdown](https://github.com/mohamedmansour/ethereum-burn-stats/blob/main/frontend/src/pages/Dashboard.tsx#L52) we just extract `timePerBlockInMs`  from `useEthereum`  so we update the activation cooldown (for mainnet launch)

2) Refactor out the calculation for time to a utility class under `frontend/src/utils/time.ts` that means moving the timestamp calculation to like `getElapsedDate(blocksRemaining: number)`. After you refactor update references in `ActivationCountdown`:
   ```
    return new Date(Date.now() + timePerBlockInMs * blocksRemaining)
   ```

3) Then for the total fees burned, we can calculate really easily by getting `timePerBlockInMs` from the Ethereum Context, and we can get the current EIP-1559 genesis block number by `eth.connectedNetwork.genesis`. And call `getElapsedTime` to render it.  For the UI, maybe something like this:
![image](https://user-images.githubusercontent.com/68524/127210528-3abf3389-71ed-4dbe-9270-c3168bad1447.png)

Then something similar for `Current Session` #9 could be done!

**Comment by HeroHann** [comment]
Also a burnrate (average) per minute for 1 day; 1 week; and infinity would be great…

**Comment by mohamedmansour** [comment]
We can definitely do burn rate @HeroHann , maybe soon!

**Comment by mohamedmansour** [comment]
@HeroHann  take a look at the site again we added 1d 1w 1m all
