### ISSUE TITLE
Set the y-axis max for insights to filter outliers.

### ISSUE THREAD

**Issue by MicahZoltu** [mohamedmansour/ethereum-burn-stats#111]
![image](https://user-images.githubusercontent.com/886059/168850350-e8ea5eff-f6c8-4b5b-8097-286664019018.png)

It would be nice if the y-axis size was capped at something like 10% higher than the 95th percentile of highs or something.  This should make it so brief outliers like seen in the image above don't break usability of the dashboard for an entire year.

**Comment by mohamedmansour** [comment]
Hey @MicahZoltu  thank you! This was on my backplate as high prior. I think what I can do (given the recharts library) is specify a max Y axis range, and let everything else overflow.

I just need to figure out what the best number would be for that cap, if I just look at all the highs and calculate as you siad the 95th percentile, I think that would work, I will do it in a bit. I just pushed the change that introduces the `maxDomainY` I just need to now calculate it.

**Comment by mohamedmansour** [comment]
@MicahZoltu  this is 95th percentile 
![image](https://user-images.githubusercontent.com/68524/169145496-d49aa12f-74d7-49e8-9cef-7055d6e81a2d.png)

This is 99th percentile:
![image](https://user-images.githubusercontent.com/68524/169145597-22e82942-4282-497e-9b5e-61b995555803.png)

This is 99.9th percentile:
![image](https://user-images.githubusercontent.com/68524/169145649-81e7235b-3b8b-4ae7-ae98-874c469b0c17.png)


99th seems okay, thoughts? I deployed the updates.

**Comment by MicahZoltu** [comment]
All of them look like a significant improvement to me.  Thanks!
