### ISSUE TITLE
Change the info/description for Net Issuance

### ISSUE THREAD

**Issue by markwdalton** [mohamedmansour/ethereum-burn-stats#112]
Very minor label/info correction.

The burned, I think just to be more clear gas units versus 'gas used'.
The Net Issuance is the main issue, it should be 'rewards - burned' vs 'burned - rewards'.

The actual calculations look correct, just the 'info' description.

In:  frontend/src/config.ts
Current:
  burned: "Burned is the amount of ETH removed from circulation: gas used x base fee.",
  netIssuance: "Net Issuance the amount of new ETH coming into circulation: burned - rewards.",

Should be:
   burned: "Burned is the amount of ETH removed from circulation: gas units (limit) x (base fee)."
   netIssuance: "Net Issuance the amount of new ETH coming into circulation: rewards - burned.",

**Comment by mohamedmansour** [comment]
Thank you! It is live.
