### ISSUE TITLE
WebSocket connection error

### ISSUE THREAD

**Issue by 0x1stvan** [mohamedmansour/ethereum-burn-stats#30]
Entering the site and just the "connecting to mainnet, please wait" text is visible with the animation.

Console error:
WebSocket connection to 'wss://watchtheburn.com/ws' failed:

**Comment by mohamedmansour** [comment]
Is it still down? We had OOM in Geth instance this morning, and I recovered by upgrading the node from 16GB ram to 32GB ram

**Comment by 0x1stvan** [comment]
It's good now.

**Comment by mohamedmansour** [comment]
More instability will come soon, since we are doing massive rework on geth <-> client communication through a cached proxy. Hopefully will make it extremely faster on high load.
