### ISSUE TITLE
Latest Stats Proposal

### ISSUE THREAD

**Issue by hanniabu** [mohamedmansour/ethereum-burn-stats#55]
It would be nice to add the average ETH burnt per day since 159 launched. I'd imagine it's a fairly simple calculation, something along the lines of: 

**average burnt per day = (total burnt) / ( [(current epoch)-(start epoch)] \ 86400)**

Current:

| Latest Stats ||
| --- | --- |
Base Fee | 56 GWEI
Watching the Burn | 297 users

Proposed:

| Latest Stats ||
| --- | --- |
Base Fee | 56 GWEI
Ave Burn Per Day | 4,567.89 ETH
Watching the Burn | 297 users

**Comment by mohamedmansour** [comment]
Yes on the pipeline :D /cc @stevengcook

**Comment by mohamedmansour** [comment]
@hanniabu  it now looks like this, we have aggregations for 1d 7d 1m and all
![image](https://user-images.githubusercontent.com/68524/132480081-b3858849-ca8d-4035-b818-8d9e85b99158.png)
